version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.14.2
    commands:
      - n 16.14.2
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
cache:
  paths:
    - node_modules/**/*
artifacts:
  files:
    - /dist/**/*
  name: takeaway-bet-dist
